title: vondrak's soapbox
tagline: a tech blog
description: >
  <img src="https://avatars.githubusercontent.com/u/600924" width="128" height="128">
  The technical writings of
  <a href="https://github.com/ajvondrak">@ajvondrak</a>
url: https://vondrak.dev
baseurl: /
paginate: 5
permalink: pretty
excerpt_separator: <!-- more -->

author:
  name: Alex Vondrak
  uri: https://vondrak.dev/
