title: vondrak's soapbox
tagline:
description:
url: https://ajvondrak.github.io/
baseurl: /soapbox
paginate: 5
permalink: pretty
excerpt_separator: <!-- more -->

author:
  name: Alex Vondrak
  uri: https://ajvondrak.github.io/soapbox
